version: '3.8'

services:
  sfdx-dev:
    profiles:
      - development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - lwc-dev:/volume/lwc-dev
      - lwc-root:/root

volumes:
  lwc-dev:
  lwc-root: