version: '3.8'

services:
  sfdx-dev:
    profiles:
      - development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - lwc-dev:/volume/lwc-dev
      - vscode-extensions:/root/.vscode-server/extensions
      - sfdx-extensions:/root/.local/share/sfdx

volumes:
  lwc-dev:
  vscode-extensions:
  sfdx-extensions: